spring.application.name=farmflow-api

spring.datasource.url=jdbc:postgresql://localhost:5432/farmflow
spring.datasource.username=farmflow_user
spring.datasource.password=farmflow_user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8082
weather.api.key=1ad56a612f5cb25a254eefa4ed0eba72
weather.api.url=https://api.openweathermap.org/data/2.5/forecast
